import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Providers } from "@/providers";
import { PanelLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NavBreadcrumbs } from "@/components/nav-breadcrumbs";
import { SearchDialog } from "@/components/search/dialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppSidebar />
          <div className="w-full">
            <nav className="h-14 p-2 space-x-4 border-b flex items-center sticky top-0 left-0 bg-background">
              <SidebarTrigger />
              <NavBreadcrumbs />
            </nav>
            <main className="p-4">{children}</main>
          </div>

          <SearchDialog />
        </Providers>
      </body>
    </html>
  );
}
